services:
  arquisis-database:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: on-failure

  arquisis-api:
    image: api:latest
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8001-8003:8000"
    depends_on:
      - arquisis-database
      - arquisis-publisher
    environment:
      ENV: production
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@arquisis-database:5432/${POSTGRES_DB_NAME}
      POST_TOKEN: ${POST_TOKEN}
      PATH_FIXTURES: ${PATH_FIXTURES}
      PATH_REQUESTS: ${PATH_REQUESTS}

      PUBLISHER_HOST: arquisis-publisher
      PUBLISHER_PORT: 7999

      JOBS_MASTER_HOST: arquisis-jobs-master
      JOBS_MASTER_PORT: 7998

      GROUP_ID: ${GROUP_ID}

      BET_PRICE: 1000
      BET_LIMIT: 40
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure

  arquisis-listener:
    image: listener:latest
    build:
      context: ./listener
      dockerfile: Dockerfile
    depends_on:
      - arquisis-api
    environment:
      ENV: production

      MQTT_HOST: ${MQTT_HOST}
      MQTT_PORT: ${MQTT_PORT}
      MQTT_USER: ${MQTT_USER}
      MQTT_PASSWORD: ${MQTT_PASSWORD}

      PATH_FIXTURES: ${PATH_FIXTURES}
      PATH_REQUESTS: ${PATH_REQUESTS}
      POST_TOKEN: ${POST_TOKEN}
      API_HOST: arquisis-api
      API_PORT: 8000
    restart: on-failure

  arquisis-publisher:
    image: publisher:latest
    build:
      context: ./publisher
      dockerfile: Dockerfile
    environment:
      ENV: production

      MQTT_HOST: ${MQTT_HOST}
      MQTT_PORT: ${MQTT_PORT}
      MQTT_USER: ${MQTT_USER}
      MQTT_PASSWORD: ${MQTT_PASSWORD}

      POST_TOKEN: ${POST_TOKEN}
    restart: on-failure

  arquisis-jobs-master:
    image: jobs-master:latest
    ports:
      - "7998:7998"
    build:
      context: ./jobs_master
      dockerfile: Dockerfile
    environment:
      ENV: production
      JOBS_USER: ${JOBS_BROKER_USER}
      JOBS_PASSWORD: ${JOBS_BROKER_PASSWORD}
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: ${JOBS_BROKER_USER}
      RABBITMQ_DEFAULT_PASS: ${JOBS_BROKER_PASSWORD}
    restart: on-failure
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 10s
      timeout: 10s
      retries: 5

volumes:
  db_data:
  rabbitmq_data:
