version: '3.8'

services:
  arquisis-database:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data

  arquisis-api:
    image: api:latest
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8001-8003:8000"
    depends_on:
      - arquisis-database
    environment:
      ENV: production
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@arquisis-database:5432/${POSTGRES_DB_NAME}
      POST_TOKEN: ${POST_TOKEN}
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure

  arquisis-mqtt:
    image: mqtt:latest
    build:
      context: ./mqtt
      dockerfile: Dockerfile
    depends_on:
      - arquisis-api
    environment:
      ENV: production
      API_HOST: arquisis-api
      API_PORT: 8000
      MQTT_HOST: ${MQTT_HOST}
      MQTT_PORT: ${MQTT_PORT}
      MQTT_USER: ${MQTT_USER}
      MQTT_PASSWORD: ${MQTT_PASSWORD}
      POST_TOKEN: ${POST_TOKEN}

volumes:
  db_data:
