version: '3.8'

services:
  api:
    image: api:latest
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8001-8003:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      POST_TOKEN: ${POST_TOKEN}
      PUBLISH_REQUESTS_URL: ${PUBLISH_REQUESTS_URL}
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure

  fixtures:_info:
    image: fixtures_info:latest
    build:
      context: ./mqtt/fixtures_info
      dockerfile: Dockerfile
    depends_on:
      - api
    environment:
      HOST: ${MQTT_HOST}
      PORT: ${MQTT_PORT}
      USER: ${MQTT_USER}
      PASSWORD: ${MQTT_PASSWORD}
      TOPIC: ${INFO_TOPIC}
      POST_TOKEN: ${POST_TOKEN}
      API_URL: ${INFO_URL}

  fixtures_requests_api:
    image: fixtures_requests_api:latest
    build:
      context: ./mqtt/fixtures_requests/app
      dockerfile: Dockerfile
    depends_on:
      - api
    environment:
      HOST: ${MQTT_HOST}
      PORT: ${MQTT_PORT}
      USER: ${MQTT_USER}
      PASSWORD: ${MQTT_PASSWORD}
      TOPIC: ${REQUESTS_TOPIC}
      POST_TOKEN: ${POST_TOKEN}
      API_URL: ${REQUESTS_URL}

  fixtures_requests_listener:
    image: fixtures_requests_api:latest
    build:
      context: ./mqtt/fixtures_requests
      dockerfile: Dockerfile
    depends_on:
      - fixtures_requests_api
    environment:
      HOST: ${MQTT_HOST}
      PORT: ${MQTT_PORT}
      USER: ${MQTT_USER}
      PASSWORD: ${MQTT_PASSWORD}
      TOPIC: ${REQUESTS_TOPIC}
      POST_TOKEN: ${POST_TOKEN}
      API_URL: ${REQUESTS_API_URL}

  fixtures_validation:
    image: fixtures_validation:latest
    build:
      context: ./mqtt/fixtures_validation
      dockerfile: Dockerfile
    depends_on:
      - api
    environment:
      HOST: ${MQTT_HOST}
      PORT: ${MQTT_PORT}
      USER: ${MQTT_USER}
      PASSWORD: ${MQTT_PASSWORD}
      TOPIC: ${VALIDATION_TOPIC}
      POST_TOKEN: ${POST_TOKEN}
      API_URL: ${VALIDATION_URL}

  fixtures_history:
    image: fixtures_history:latest
    build:
      context: ./mqtt/fixtures_history
      dockerfile: Dockerfile
    depends_on:
      - api
    environment:
      HOST: ${MQTT_HOST}
      PORT: ${MQTT_PORT}
      USER: ${MQTT_USER}
      PASSWORD: ${MQTT_PASSWORD}
      TOPIC: ${HISTORY_TOPIC}
      POST_TOKEN: ${POST_TOKEN}
      API_URL: ${HISTORY_URL}

  db:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
