version: '3'

services:
  newrelic-infra:
    container_name: newrelic-infra
    build:
      context: ./newrelic-infra
      dockerfile: newrelic-infra.dockerfile
    cap_add:
      - SYS_PTRACE
    network_mode: host
    pid: host
    privileged: true
    entrypoint: ["/tini", "--"]
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/proc:/host/proc:ro"
    environment:
      - NRIA_LICENSE_KEY=${NEW_RELIC_LICENSE_KEY}
      - NRIA_VERBOSE=0
      - NRIA_DISABLE_SAMPLERS=NetworkSampler,StorageSampler
    restart: unless-stopped


