name: Build and Deploy

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: build_test_env

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2
    
    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose --version

    - name: Build Docker images
      run: docker-compose build

    - name: Run Docker containers
      run: docker-compose up -d
      env:
        POSTGRES_USER: ${{ vars.POSTGRES_USER }}
        POSTGRES_PASSWORD: ${{ vars.POSTGRES_PASSWORD }}
        POSTGRES_DB_NAME: ${{ vars.POSTGRES_DB_NAME }}
        POST_TOKEN: ${{ vars.POST_TOKEN }}
        PATH_FIXTURES: ${{ vars.PATH_FIXTURES }}
        PATH_REQUESTS: ${{ vars.PATH_REQUESTS }}
        MQTT_HOST: ${{ secrets.MQTT_HOST }}
        MQTT_PORT: ${{ secrets.MQTT_PORT }}
        MQTT_USER: ${{ secrets.MQTT_USER }}
        MQTT_PASSWORD: ${{ secrets.MQTT_PASSWORD }}
        GROUP_ID: ${{ vars.GROUP_ID }}
        TRANSBANK_REDIRECT_URL: ${{ vars.TRANSBANK_REDIRECT_URL }}
        SESSION_ID: ${{ vars.SESSION_ID }}
        ENV: production

    - name: Install Python
      run: sudo apt-get install -y python3 python3-pip

    - name: Install Requests library
      run: pip3 install requests
    
    - name: Wait for containers to start
      run: sleep 20

    - name: Run API tests
      run: python3 test_services.py
      env:
        PATH_FIXTURES: ${{ vars.PATH_FIXTURES }}
        ENV: production

    - name: Check Listener Logs
      run: docker-compose logs arquisis-listener | grep "Connected to Broker with result code" || exit 1

    - name: Stop containers
      run: docker-compose down

  deploy:
    needs: build
    if: github.ref == 'refs/heads/main' && success()
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        port: 22
        script: |
          cd ./arqui-backend
          git pull origin main
          docker-compose down
          docker-compose up --build -d