name: Build and Deploy

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Build Docker images
      run: docker-compose build

    - name: Run Docker containers
      run: docker-compose up -d

    - name: Install Python
      run: sudo apt-get install -y python3 python3-pip

    - name: Install Requests library
      run: pip3 install requests

    - name: Run API tests
      run: python3 test_services.py

    - name: Check Listener Logs
      run: |
        sleep 10
        docker-compose logs arquisis-listener | grep "Connected to Broker with result code" || exit 1

    - name: Stop containers
      run: docker-compose down

  deploy:
    needs: build
    if: github.ref == 'refs/heads/main' && success()
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        port: 22
        script: |
          cd /arquisis-backend
          git pull origin main
          docker-compose down
          docker-compose up --build -d