name: Release

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - 'terraform/**'

permissions:
  id-token: write
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Semantic Release
        id: semantic_release
        uses: cycjimmy/semantic-release-action@v4
        env:
            GH_TOKEN: ${{ secrets.GIT_TOKEN }}