name: Test and Deploy Serverless Function

on:
  push:
    branches:
      - main
    paths:
      - 'generar_boleta/**'
      - '.github/workflows/test_and_deploy_serverless.yaml'

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8

      - name: Package Lambda Function
        run: |
          cd generar_boleta
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          mkdir -p .venv/lib/python3.12/site-packages
          pip install --target .venv/lib/python3.12/site-packages -r requirements.txt
          cd .venv/lib/python3.12/site-packages
          zip -r9 ${OLDPWD}/function.zip .
          cd ${OLDPWD}
          zip -g function.zip handler.py

      - name: serverless deploy
        uses: serverless/github-action@v3.2
        with:
          args: deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}